name: Build and Commit PDF
on: [push]

jobs:
    build:
        name: Build PDF
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        - name: Checkout master
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - uses: typst-community/setup-typst@v3
          id: setup-typst

        - name: Build PDF
          run: 'make all'

        - name: Release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: PDF
            name: PDF
            body: Compiled PDF resume
            draft: false
            prerelease: false
            files: |
              Resume_CN.pdf
              Resume_EN.pdf


